name: pr test
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: docker buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          usr: ${{ secrets.DOCKERHUB_USERNAME }}
          pw: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build + push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: aweksa/intens-praksa:latest
     
        
